#!/usr/bin/env python3
"""Print an apply_patch patch for pinned, licensed Phosphor vectors. Never edits source."""
import concurrent.futures
import json
import difflib
from pathlib import Path
import urllib.request
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
revision = '2b75f3ad12b420c9504ef05df8d2564a28f8500e'
mapping = json.loads((root / 'scripts/novex-icon-map.json').read_text())

def load(name):
    url = f'https://raw.githubusercontent.com/phosphor-icons/core/{revision}/assets/regular/{name}.svg'
    with urllib.request.urlopen(url, timeout=30) as response:
        svg = ET.fromstring(response.read())
    elements = list(svg)
    assert all(e.tag.rsplit('}', 1)[-1] == 'path' for e in elements), name
    return name, [e.attrib['d'] for e in elements]

with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
    paths = dict(pool.map(load, sorted(set(mapping.values()))))

source = '''package com.openminis.app.ui.novex

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/** Phosphor regular icons, pinned to REVISION; MIT license in res/raw/phosphor_icons_license.txt.
 * Generated by scripts/generate_novex_icons.py. Icons are parsed lazily, only when that icon is first used.
 */
internal object NovexIcons {
'''.replace('REVISION', revision)
for old, name in sorted(mapping.items()):
    identifier = 'asset_' + name.replace('-', '_')
    source += f'    val {old}: ImageVector get() = {identifier}\n'
for name, commands in sorted(paths.items()):
    identifier = 'asset_' + name.replace('-', '_')
    auto_mirror = name in ['arrow-left','arrow-right','caret-left','caret-right','arrow-u-up-left','arrow-elbow-down-left']
    source += f'    private val {identifier} by lazy {{\n        ImageVector.Builder(name = "{name}", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 256f, viewportHeight = 256f, autoMirror = {str(auto_mirror).lower()}).apply {{\n'
    for path in commands:
        source += '            addPath(pathData = PathParser().parsePathString(' + json.dumps(path) + ').toNodes(), fill = SolidColor(Color.Black))\n'
    source += '        }.build()\n    }\n'
source += '}\n'
target = root / 'src/android/app/src/main/java/com/openminis/app/ui/novex/NovexIcons.kt'
if target.exists() and target.read_text() == source:
    print('*** Begin Patch\n*** End Patch')
    raise SystemExit(0)
print('*** Begin Patch')
if target.exists():
    print('*** Update File: ' + str(target))
    for line in list(difflib.unified_diff(target.read_text().splitlines(True), source.splitlines(True)))[2:]:
        print('@@' if line.startswith('@@') else line.rstrip('\n'))
else:
    print('*** Add File: ' + str(target))
    print('\n'.join('+' + line for line in source.splitlines()))
print('*** End Patch')
